/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: ../sanity.schema.json
export type SplitContentLink = {
  label?: string
  link?: Link
}

export type RequirementsListLink = {
  label?: string
  link?: Link
}

export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type TeamMemberImage = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "teamMember.image.media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  _type: 'image'
}

export type ServiceCardImage = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "serviceCard.image.media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  _type: 'image'
}

export type ObjectImage = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "object.image.media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  _type: 'image'
}

export type FeaturesObjectImage = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "features.object.image.media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  _type: 'image'
}

export type ColumnsObjectImage = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "columns.object.image.media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  _type: 'image'
}

export type LogosObjectImage = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "logos.object.image.media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  _type: 'image'
}

export type ItemsObjectImage = {
  asset?: SanityImageAssetReference
  media?: unknown // Unable to locate the referenced type "items.object.image.media" in schema
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  _type: 'image'
}

export type TableData = {
  categories?: Array<{
    categoryName?: string
    tiers?: Array<{
      name?: string
      price?: string
      description?: string
      features?: Array<string>
      highlighted?: boolean
      _type: 'pricingTier'
      _key: string
    }>
    _type: 'pricingCategory'
    _key: string
  }>
  description?: string
}

export type MatrixData = {
  description?: string
  tables?: Array<{
    tableName?: string
    tableDescription?: string
    columnHeaders?: Array<string>
    rows?: Array<{
      rowLabel?: string
      cells?: Array<{
        value?: string
        note?: string
        _type: 'matrixCell'
        _key: string
      }>
      _type: 'matrixRow'
      _key: string
    }>
    _type: 'matrixTable'
    _key: string
  }>
  footnotes?: Array<string>
}

export type Spacer = {
  _type: 'spacer'
  size?: 'sm' | 'md' | 'lg' | 'xl'
}

export type PhotoMarquee = {
  _type: 'photoMarquee'
  marqueeImages?: Array<{
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
    _key: string
  }>
}

export type PricingPageTabs = {
  _type: 'pricingPageTabs'
  eyebrow?: string
  heading: string
  description?: string
  defaultTab?: 'daycare' | 'boarding' | 'grooming'
  services?: Array<{
    serviceKey: 'daycare' | 'boarding' | 'grooming'
    pricingDisplay?: 'table' | 'matrix'
    tableData?: TableData
    matrixData?: MatrixData
    showCalculator?: boolean
    _key: string
  }>
  ctaText?: string
  ctaLink?: Link
  taxNote?: string
}

export type ValuePillars = {
  _type: 'valuePillars'
  eyebrow?: string
  heading?: string
  description?: string
  pillars?: Array<{
    metric: string
    title: string
    description?: string
    _key: string
  }>
  columns?: 2 | 3 | 4
  accentImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  backgroundColor?: 'cream' | 'sand' | 'forest'
}

export type GalleryPage = {
  _type: 'galleryPage'
  heading?: string
  subtext?: string
  images?: Array<{
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    caption?: string
    span?: 1 | 2
    _type: 'image'
    _key: string
  }>
  layout?: 'grid' | 'single'
  backgroundColor?: 'cream' | 'sand'
}

export type GalleryShowcase = {
  _type: 'galleryShowcase'
  eyebrow?: string
  heading?: string
  subheading?: string
  images?: Array<{
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    caption?: string
    _type: 'image'
    _key: string
  }>
  backgroundColor?: 'cream' | 'sand'
}

export type GalleryCarousel = {
  _type: 'galleryCarousel'
  eyebrow?: string
  heading?: string
  images?: Array<{
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    caption?: string
    _type: 'image'
    _key: string
  }>
  enableLightbox?: boolean
  backgroundColor?: 'cream' | 'sand' | 'forest'
}

export type RequirementsList = {
  _type: 'requirementsList'
  eyebrow?: string
  heading: string
  description?: string
  items?: Array<{
    text?: string
    _type: 'item'
    _key: string
  }>
  link?: RequirementsListLink
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  imagePosition?: 'left' | 'right'
  backgroundColor?: 'cream' | 'sand'
}

export type WhatsIncluded = {
  _type: 'whatsIncluded'
  eyebrow?: string
  heading?: string
  description?: string
  items?: Array<{
    icon?: string
    title: string
    description?: string
    _key: string
  }>
  layout?: 'card' | 'inline'
  columns?: 2 | 3 | 4
  backgroundColor?: 'cream' | 'sand' | 'forest'
  iconColor?: 'terracotta' | 'forest' | 'muted'
}

export type PricingCalculator = {
  _type: 'pricingCalculator'
  displayMode?: 'single' | 'tabbed'
  calculatorType?: 'daycare' | 'boarding' | 'grooming'
  eyebrow?: string
  heading: string
  subheading?: string
  ctaText?: string
  ctaLink?: Link
  taxNote?: string
}

export type FeatureGrid = {
  _type: 'featureGrid'
  heading: string
  cta?: Button
  items?: Array<{
    image?: ItemsObjectImage
    icon?: string
    title: string
    description?: string
    _key: string
  }>
  columns?: 3 | 4
  backgroundColor?: 'cream' | 'sand' | 'forest' | 'black'
}

export type PolicyNotes = {
  _type: 'policyNotes'
  eyebrow?: string
  heading?: string
  categories?: Array<{
    categoryName: string
    policies?: Array<string>
    _type: 'policyCategory'
    _key: string
  }>
  backgroundColor?: 'cream' | 'sand' | 'forest'
}

export type PricingList = {
  _type: 'pricingList'
  eyebrow?: string
  heading?: string
  description?: string
  items?: Array<{
    service: string
    price?: string
    note?: string
    _type: 'pricingListItem'
    _key: string
  }>
  columns?: 1 | 2
  backgroundColor?: 'cream' | 'sand'
}

export type PricingMatrix = {
  _type: 'pricingMatrix'
  eyebrow?: string
  heading?: string
  description?: string
  tables?: Array<{
    tableName: string
    tableDescription?: string
    columnHeaders?: Array<string>
    rows?: Array<{
      rowLabel: string
      cells?: Array<{
        value?: string
        note?: string
        _type: 'matrixCell'
        _key: string
      }>
      _type: 'matrixRow'
      _key: string
    }>
    _type: 'matrixTable'
    _key: string
  }>
  footnotes?: Array<string>
  backgroundColor?: 'cream' | 'sand'
}

export type LogoBar = {
  _type: 'logoBar'
  heading?: string
  logos?: Array<{
    image: LogosObjectImage
    alt: string
    url?: string
    _key: string
  }>
  displayMode?: 'grid' | 'marquee'
  backgroundColor?: 'cream' | 'sand' | 'white'
}

export type CtaStrip = {
  _type: 'ctaStrip'
  heading: string
  subtext?: string
  cta: Button
  backgroundColor?: 'cream' | 'sand' | 'forest' | 'terracotta'
}

export type FullWidthMedia = {
  _type: 'fullWidthMedia'
  heading?: string
  subtext?: string
  cta?: Button
  image: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  textAlignment?: 'left' | 'center' | 'right'
  overlayOpacity?: 'light' | 'medium' | 'heavy'
}

export type VideoSection = {
  _type: 'videoSection'
  eyebrow?: string
  heading?: string
  description?: string
  primaryCta?: Button
  secondaryCta?: Button
  videoUrl: string
  thumbnail?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  layout?: 'full' | 'split'
  backgroundColor?: 'cream' | 'sand' | 'forest'
}

export type IconGrid = {
  _type: 'iconGrid'
  eyebrow?: string
  heading: string
  description?: string
  items?: Array<{
    icon?: string
    title: string
    description?: string
    _key: string
  }>
  columns?: 2 | 3 | 4
  accentImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  backgroundColor?: 'cream' | 'sand' | 'forest'
}

export type ContentColumns = {
  _type: 'contentColumns'
  eyebrow?: string
  heading?: string
  columns?: Array<{
    image?: ColumnsObjectImage
    heading?: string
    body?: BlockContent
    cta?: Button
    _key: string
  }>
  layout?: 2 | 3
  backgroundColor?: 'cream' | 'sand'
}

export type ProcessSteps = {
  _type: 'processSteps'
  eyebrow?: string
  heading: string
  description?: string
  steps?: Array<{
    title: string
    badge?: string
    description?: string
    icon?: string
    _type: 'step'
    _key: string
  }>
  cta?: Button
  backgroundColor?: 'cream' | 'sand' | 'forest'
}

export type FeatureList = {
  _type: 'featureList'
  eyebrow?: string
  heading: string
  features?: Array<{
    title: string
    body?: BlockContent
    image?: FeaturesObjectImage
    cta?: Button
    _key: string
  }>
  showNumbers?: boolean
  backgroundColor?: 'cream' | 'sand'
}

export type ExpandingCardsRow = {
  _type: 'expandingCardsRow'
  eyebrow?: string
  heading: string
  subheading?: string
  cards?: Array<{
    image: ObjectImage
    title: string
    subtext?: string
    link?: Button
    _key: string
  }>
  backgroundColor?: 'cream' | 'sand'
}

export type ServiceCards = {
  _type: 'serviceCards'
  eyebrow?: string
  heading: string
  description?: string
  cards?: Array<{
    image?: ServiceCardImage
    title: string
    description?: string
    cta?: Button
    _type: 'serviceCard'
    _key: string
  }>
  variant?: 'white' | 'imageOverlay'
  columns?: 2 | 3 | 4
  backgroundColor?: 'cream' | 'sand'
}

export type HeroMinimal = {
  _type: 'heroMinimal'
  eyebrow?: string
  rating?: string
  heading: string
  headingAccent?: string
  subtext?: string
  backgroundColor?: 'cream' | 'sand' | 'forest'
}

export type HeroMarquee = {
  _type: 'heroMarquee'
  eyebrow?: string
  heading: string
  headingAccent?: string
  subtext?: string
  primaryCta?: Button
  secondaryCta?: Button
  reviewRating?: number
  reviewText?: string
  trustLine?: string
  bubbleText?: string
  heroLogo?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  marqueeImages?: Array<{
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
    _key: string
  }>
}

export type HeroBanner = {
  _type: 'heroBanner'
  eyebrow?: string
  heading: string
  subtext?: string
  primaryCta?: Button
  backgroundImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  overlayOpacity?: 'light' | 'medium' | 'heavy'
  minHeight?: 'standard' | 'tall' | 'fullscreen'
  backgroundColor?: 'cream' | 'sand' | 'forest'
}

export type HeroSplit = {
  _type: 'heroSplit'
  eyebrow?: string
  heading: string
  body?: string
  primaryCta?: Button
  secondaryCta?: Button
  image: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  stickerImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  imagePosition?: 'left' | 'right'
  backgroundColor?: 'cream' | 'sand' | 'forest'
}

export type ContactForm = {
  _type: 'contactForm'
  eyebrow?: string
  heading: string
  description?: BlockContent
  formFields?: Array<{
    fieldName: string
    label: string
    type?: 'text' | 'email' | 'tel' | 'textarea' | 'select'
    required?: boolean
    options?: Array<string>
    _type: 'formField'
    _key: string
  }>
  submitButtonText?: string
  successMessage?: string
  showMap?: boolean
  mapEmbedUrl?: string
  nextSteps?: Array<{
    title: string
    description?: string
    _type: 'nextStep'
    _key: string
  }>
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  address?: string
  phone?: string
  email?: string
  hours?: Array<{
    label: string
    value: string
    _type: 'hoursEntry'
    _key: string
  }>
}

export type GalleryGrid = {
  _type: 'galleryGrid'
  eyebrow?: string
  heading?: string
  images?: Array<{
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    caption?: string
    _type: 'image'
    _key: string
  }>
  columns?: 2 | 3 | 4
  displayStyle?: 'grid' | 'circles'
  enableLightbox?: boolean
  accentImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  backgroundColor?: 'cream' | 'sand' | 'forest'
}

export type TeamGrid = {
  _type: 'teamGrid'
  eyebrow?: string
  heading?: string
  members?: Array<{
    name: string
    role?: string
    bio?: string
    certifications?: string
    image?: TeamMemberImage
    _type: 'teamMember'
    _key: string
  }>
}

export type PricingTable = {
  _type: 'pricingTable'
  eyebrow?: string
  heading?: string
  description?: string
  categories?: Array<{
    categoryName: string
    tiers?: Array<{
      name: string
      price?: string
      description?: string
      features?: Array<string>
      highlighted?: boolean
      cta?: Button
      _type: 'pricingTier'
      _key: string
    }>
    _type: 'pricingCategory'
    _key: string
  }>
}

export type FaqAccordion = {
  _type: 'faqAccordion'
  eyebrow?: string
  heading: string
  faqs?: Array<{
    question: string
    answer?: BlockContent
    _type: 'faq'
    _key: string
  }>
}

export type SplitContent = {
  _type: 'splitContent'
  heading: string
  body?: BlockContent
  link?: SplitContentLink
  badge?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  stickerImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  hours?: Array<{
    label: string
    value: string
    _type: 'hoursEntry'
    _key: string
  }>
  imagePosition?: 'left' | 'right'
  backgroundColor?: 'cream' | 'sand' | 'forest'
}

export type CtaBanner = {
  _type: 'ctaBanner'
  icon?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  stickerImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  heading: string
  subtext?: string
  backgroundImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  sideImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  cta?: Button
  alignment?: 'center' | 'left'
  showRating?: boolean
  ratingText?: string
}

export type TestimonialReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'testimonial'
}

export type Testimonials = {
  _type: 'testimonials'
  icon?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  heading: string
  reviews?: Array<
    {
      _key: string
    } & TestimonialReference
  >
  googleRating?: string
  googleReviewCount?: number
}

export type StatsBar = {
  _type: 'statsBar'
  stats?: Array<{
    value: string
    label: string
    _type: 'statItem'
    _key: string
  }>
  showLogo?: boolean
}

export type ServiceReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'service'
}

export type ServiceTabs = {
  _type: 'serviceTabs'
  eyebrow?: string
  heading: string
  tabs?: Array<
    {
      _key: string
    } & ServiceReference
  >
}

export type FeatureCards = {
  _type: 'featureCards'
  heading: string
  subheading?: string
  stickerLeft?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  stickerRight?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  features?: Array<{
    icon?: string
    title: string
    description?: string
    _key: string
  }>
  cta?: Button
  trustLine?: string
  columns?: 3 | 4
  darkMode?: boolean
}

export type ImageRow = {
  _type: 'imageRow'
  images?: Array<{
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
    _key: string
  }>
}

export type Hero = {
  _type: 'hero'
  eyebrow?: string
  heading: string
  subtext?: string
  primaryCta?: Button
  secondaryCta?: Button
  reviewRating?: number
  reviewText?: string
  trustLine?: string
  heroImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  carouselImages?: Array<{
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
    _key: string
  }>
}

export type PageReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'page'
}

export type Link = {
  _type: 'link'
  linkType?: 'href' | 'page'
  href?: string
  page?: PageReference | ServiceReference
  queryString?: string
  openInNewTab?: boolean
}

export type CallToAction = {
  _type: 'callToAction'
  eyebrow?: string
  heading: string
  body?: BlockContentTextOnly
  button?: Button
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  theme?: 'light' | 'dark'
  contentAlignment?: 'textFirst' | 'imageFirst'
}

export type InfoSection = {
  _type: 'infoSection'
  heading?: string
  subheading?: string
  content?: BlockContent
}

export type BlockContentTextOnly = Array<{
  children?: Array<{
    marks?: Array<string>
    text?: string
    _type: 'span'
    _key: string
  }>
  style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
  listItem?: 'bullet' | 'number'
  markDefs?: Array<{
    href?: string
    _type: 'link'
    _key: string
  }>
  level?: number
  _type: 'block'
  _key: string
}>

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        linkType?: 'href' | 'page'
        href?: string
        page?: PageReference
        openInNewTab?: boolean
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }
  | {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
      _key: string
    }
>

export type Button = {
  _type: 'button'
  buttonText?: string
  link?: Link
}

export type Seo = {
  _type: 'seo'
  metaTitle?: string
  metaDescription?: string
  ogImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  noIndex?: boolean
}

export type Testimonial = {
  _id: string
  _type: 'testimonial'
  _createdAt: string
  _updatedAt: string
  _rev: string
  quote: string
  authorName: string
  authorLabel?: string
  rating?: number
}

export type Service = {
  _id: string
  _type: 'service'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug?: Slug
  sticker?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  shortDescription?: string
  tabImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  tabCta?: Button
  heading?: string
  seo?: Seo
  pageBuilder?: Array<
    | ({
        _key: string
      } & CallToAction)
    | ({
        _key: string
      } & InfoSection)
    | ({
        _key: string
      } & Hero)
    | ({
        _key: string
      } & ImageRow)
    | ({
        _key: string
      } & FeatureCards)
    | ({
        _key: string
      } & ServiceTabs)
    | ({
        _key: string
      } & StatsBar)
    | ({
        _key: string
      } & Testimonials)
    | ({
        _key: string
      } & CtaBanner)
    | ({
        _key: string
      } & SplitContent)
    | ({
        _key: string
      } & FaqAccordion)
    | ({
        _key: string
      } & PricingTable)
    | ({
        _key: string
      } & TeamGrid)
    | ({
        _key: string
      } & GalleryGrid)
    | ({
        _key: string
      } & ContactForm)
    | ({
        _key: string
      } & HeroSplit)
    | ({
        _key: string
      } & HeroBanner)
    | ({
        _key: string
      } & ServiceCards)
    | ({
        _key: string
      } & ExpandingCardsRow)
    | ({
        _key: string
      } & FeatureList)
    | ({
        _key: string
      } & ProcessSteps)
    | ({
        _key: string
      } & ContentColumns)
    | ({
        _key: string
      } & IconGrid)
    | ({
        _key: string
      } & VideoSection)
    | ({
        _key: string
      } & FullWidthMedia)
    | ({
        _key: string
      } & CtaStrip)
    | ({
        _key: string
      } & LogoBar)
    | ({
        _key: string
      } & HeroMarquee)
    | ({
        _key: string
      } & HeroMinimal)
    | ({
        _key: string
      } & PricingMatrix)
    | ({
        _key: string
      } & PricingList)
    | ({
        _key: string
      } & PolicyNotes)
    | ({
        _key: string
      } & FeatureGrid)
    | ({
        _key: string
      } & PricingCalculator)
    | ({
        _key: string
      } & WhatsIncluded)
    | ({
        _key: string
      } & RequirementsList)
    | ({
        _key: string
      } & GalleryCarousel)
    | ({
        _key: string
      } & GalleryShowcase)
    | ({
        _key: string
      } & ValuePillars)
    | ({
        _key: string
      } & PhotoMarquee)
    | ({
        _key: string
      } & Spacer)
  >
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top: number
  bottom: number
  left: number
  right: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x: number
  y: number
  height: number
  width: number
}

export type Slug = {
  _type: 'slug'
  current: string
  source?: string
}

export type Settings = {
  _id: string
  _type: 'settings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  tagline?: string
  description?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: Array<{
      linkType?: 'href' | 'page'
      href?: string
      page?: PageReference
      openInNewTab?: boolean
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  logo?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  navItems?: Array<{
    label: string
    link?: Link
    children?: Array<{
      label?: string
      link?: Link
      _key: string
    }>
    _type: 'navItem'
    _key: string
  }>
  ctaButton?: Button
  footerSticker?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  footerTagline?: string
  footerColumns?: Array<{
    title?: string
    links?: Array<{
      label?: string
      link?: Link
      _key: string
    }>
    _key: string
  }>
  contactInfo?: {
    address?: string
    phone?: string
    email?: string
  }
  footerText?: string
  footerTextLink?: {
    label?: string
    href?: string
  }
  footerBottomLinks?: Array<{
    label?: string
    link?: Link
    _key: string
  }>
  yearEstablished?: number
  socialLinks?: {
    facebook?: string
    instagram?: string
    google?: string
  }
  posUrls?: {
    portalUrl?: string
    registrationUrl?: string
    daycareBookingUrl?: string
    boardingBookingUrl?: string
    groomingBookingUrl?: string
    transportationBookingUrl?: string
  }
  ogImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    metadataBase?: string
    _type: 'image'
  }
  favicon?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  ga4MeasurementId?: string
  gtmContainerId?: string
  googleSiteVerification?: string
  localBusiness?: {
    businessName?: string
    businessType?: string
    address?: {
      street?: string
      city?: string
      state?: string
      zip?: string
      country?: string
    }
    phone?: string
    geoCoordinates?: {
      latitude?: number
      longitude?: number
    }
    businessHours?: Array<{
      days?: string
      open?: string
      close?: string
      _key: string
    }>
    priceRange?: string
  }
}

export type Page = {
  _id: string
  _type: 'page'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  slug: Slug
  seo?: Seo
  pageBuilder?: Array<
    | ({
        _key: string
      } & CallToAction)
    | ({
        _key: string
      } & InfoSection)
    | ({
        _key: string
      } & Hero)
    | ({
        _key: string
      } & ImageRow)
    | ({
        _key: string
      } & FeatureCards)
    | ({
        _key: string
      } & ServiceTabs)
    | ({
        _key: string
      } & StatsBar)
    | ({
        _key: string
      } & Testimonials)
    | ({
        _key: string
      } & CtaBanner)
    | ({
        _key: string
      } & SplitContent)
    | ({
        _key: string
      } & FaqAccordion)
    | ({
        _key: string
      } & PricingTable)
    | ({
        _key: string
      } & TeamGrid)
    | ({
        _key: string
      } & GalleryGrid)
    | ({
        _key: string
      } & ContactForm)
    | ({
        _key: string
      } & HeroSplit)
    | ({
        _key: string
      } & HeroBanner)
    | ({
        _key: string
      } & HeroMarquee)
    | ({
        _key: string
      } & HeroMinimal)
    | ({
        _key: string
      } & ServiceCards)
    | ({
        _key: string
      } & ExpandingCardsRow)
    | ({
        _key: string
      } & FeatureList)
    | ({
        _key: string
      } & ProcessSteps)
    | ({
        _key: string
      } & ContentColumns)
    | ({
        _key: string
      } & IconGrid)
    | ({
        _key: string
      } & VideoSection)
    | ({
        _key: string
      } & FullWidthMedia)
    | ({
        _key: string
      } & CtaStrip)
    | ({
        _key: string
      } & LogoBar)
    | ({
        _key: string
      } & PricingMatrix)
    | ({
        _key: string
      } & PricingList)
    | ({
        _key: string
      } & PolicyNotes)
    | ({
        _key: string
      } & FeatureGrid)
    | ({
        _key: string
      } & PricingCalculator)
    | ({
        _key: string
      } & WhatsIncluded)
    | ({
        _key: string
      } & RequirementsList)
    | ({
        _key: string
      } & GalleryCarousel)
    | ({
        _key: string
      } & GalleryShowcase)
    | ({
        _key: string
      } & GalleryPage)
    | ({
        _key: string
      } & ValuePillars)
    | ({
        _key: string
      } & PricingPageTabs)
    | ({
        _key: string
      } & PhotoMarquee)
    | ({
        _key: string
      } & Spacer)
  >
}

export type SanityAssistInstructionTask = {
  _type: 'sanity.assist.instructionTask'
  path?: string
  instructionKey?: string
  started?: string
  updated?: string
  info?: string
}

export type SanityAssistTaskStatus = {
  _type: 'sanity.assist.task.status'
  tasks?: Array<
    {
      _key: string
    } & SanityAssistInstructionTask
  >
}

export type SanityAssistSchemaTypeAnnotations = {
  _type: 'sanity.assist.schemaType.annotations'
  title?: string
  fields?: Array<
    {
      _key: string
    } & SanityAssistSchemaTypeField
  >
}

export type SanityAssistOutputType = {
  _type: 'sanity.assist.output.type'
  type?: string
}

export type SanityAssistOutputField = {
  _type: 'sanity.assist.output.field'
  path?: string
}

export type AssistInstructionContextReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'assist.instruction.context'
}

export type SanityAssistInstructionContext = {
  _type: 'sanity.assist.instruction.context'
  reference: AssistInstructionContextReference
}

export type AssistInstructionContext = {
  _id: string
  _type: 'assist.instruction.context'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  context?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: null
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type SanityAssistInstructionUserInput = {
  _type: 'sanity.assist.instruction.userInput'
  message: string
  description?: string
}

export type SanityAssistInstructionPrompt = Array<{
  children?: Array<
    | {
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }
    | ({
        _key: string
      } & SanityAssistInstructionFieldRef)
    | ({
        _key: string
      } & SanityAssistInstructionContext)
    | ({
        _key: string
      } & SanityAssistInstructionUserInput)
  >
  style?: 'normal'
  listItem?: never
  markDefs?: null
  level?: number
  _type: 'block'
  _key: string
}>

export type SanityAssistInstructionFieldRef = {
  _type: 'sanity.assist.instruction.fieldRef'
  path?: string
}

export type SanityAssistInstruction = {
  _type: 'sanity.assist.instruction'
  prompt?: SanityAssistInstructionPrompt
  icon?: string
  title?: string
  userId?: string
  createdById?: string
  output?: Array<
    | ({
        _key: string
      } & SanityAssistOutputField)
    | ({
        _key: string
      } & SanityAssistOutputType)
  >
}

export type SanityAssistSchemaTypeField = {
  _type: 'sanity.assist.schemaType.field'
  path?: string
  instructions?: Array<
    {
      _key: string
    } & SanityAssistInstruction
  >
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height: number
  width: number
  aspectRatio: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | SplitContentLink
  | RequirementsListLink
  | SanityImageAssetReference
  | TeamMemberImage
  | ServiceCardImage
  | ObjectImage
  | FeaturesObjectImage
  | ColumnsObjectImage
  | LogosObjectImage
  | ItemsObjectImage
  | TableData
  | MatrixData
  | Spacer
  | PhotoMarquee
  | PricingPageTabs
  | ValuePillars
  | GalleryPage
  | GalleryShowcase
  | GalleryCarousel
  | RequirementsList
  | WhatsIncluded
  | PricingCalculator
  | FeatureGrid
  | PolicyNotes
  | PricingList
  | PricingMatrix
  | LogoBar
  | CtaStrip
  | FullWidthMedia
  | VideoSection
  | IconGrid
  | ContentColumns
  | ProcessSteps
  | FeatureList
  | ExpandingCardsRow
  | ServiceCards
  | HeroMinimal
  | HeroMarquee
  | HeroBanner
  | HeroSplit
  | ContactForm
  | GalleryGrid
  | TeamGrid
  | PricingTable
  | FaqAccordion
  | SplitContent
  | CtaBanner
  | TestimonialReference
  | Testimonials
  | StatsBar
  | ServiceReference
  | ServiceTabs
  | FeatureCards
  | ImageRow
  | Hero
  | PageReference
  | Link
  | CallToAction
  | InfoSection
  | BlockContentTextOnly
  | BlockContent
  | Button
  | Seo
  | Testimonial
  | Service
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | Settings
  | Page
  | SanityAssistInstructionTask
  | SanityAssistTaskStatus
  | SanityAssistSchemaTypeAnnotations
  | SanityAssistOutputType
  | SanityAssistOutputField
  | AssistInstructionContextReference
  | SanityAssistInstructionContext
  | AssistInstructionContext
  | SanityAssistInstructionUserInput
  | SanityAssistInstructionPrompt
  | SanityAssistInstructionFieldRef
  | SanityAssistInstruction
  | SanityAssistSchemaTypeField
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint

export declare const internalGroqTypeReferenceTo: unique symbol
